config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static#home'

  resources :users do
    resources :trips, only: [:index, :show, :new, :edit]
  end

  resources :trips

  resources :countries

  get '/users/most_trips_taken' => 'users#most_trips_taken'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#create'

end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  belongs_to :country
  validates :comment, length: {maximum: 100}
  validates :year, length: {is: 4}
  validate :future_trip?
  validates :country_name, presence: true
  alias_attribute :recommend, :recommend?

    def future_trip?
      if year > Time.new.year
        errors.add(:year, "cannot be in the future.")
      end
    end

    def country_name=(name)
      self.country = Country.find_or_create_by(name: name)
    end

    def country_name
      self.country.name if self.country
    end

    # Scope methods for filtering trips by year 

    def self.twentieth_century
      where('year <= ?', 2000)
    end

    def self.aughts
      where('year > ? AND year < ?', 1999, 2010)
    end

    def self.first_half_of_teens
      where('year > ? AND year < ?', 2009, 2016)
    end

    def self.second_half_of_teens
      where('year > ? AND year < ?', 2015, 2019)
    end

end

app/controllers/trips_controller.rb
require 'pry'
class TripsController < ApplicationController
  before_action :require_login

  def index
    # Getting all the trips taken by one particular user
    if params[:user_id]
      @trips = Trip.where(user_id: params[:user_id])
      render json: @trips
    end


    if !params[:year].blank?
      class_method_conditional
      @filter = params[:year]
      else
        @trips = Trip.all
      end
    end


    # Trips/new not needed as own route because form has been incorporated into users/show page
    
  # def new
  #    if params[:user_id] && !User.exists?(params[:user_id])
  #      redirect_to users_path
  #   else
  #     @trip = Trip.new(user_id: params[:user_id])
  #   end
  # end

  def create
    @trip = Trip.new(trip_params)
    @trip.user = current_user
    # If :trip :country is blank then a country was selected from the countries already present. Otherwise it is a new country being added to the database
      if params[:trip][:country] != ""
        @trip.country = Country.find_by(name: params[:trip][:country])
        saving_trip
      else
        saving_trip
      end
  end

  def edit
    @trip = Trip.find_by(id: params[:id])
    if @trip.user != current_user
      redirect_to users_path
    end
  end

  def update
    @trip = Trip.find_by(id: params[:id])
    if @trip.update(trip_params)
      redirect_to users_path
    else
      render 'edit'
    end
  end

  def show
    if params[:user_id]
      @user = User.find_by(id: params[:user_id])
      @trip = @user.trips.find_by(id: params[:id])
      respond_to do |format|
        format.html {render :show}
        format.json {render json: @trip}
      end
      if @trip.nil?
        redirect_to users_path
      end
    else
    @trip = Trip.find_by(id: params[:id])
    respond_to do |format|
      format.html {render :show}
      format.json {render json: @trip}
    end
    end
  end

  def destroy
    @trip = Trip.find(params[:id])
    @trip.delete
    redirect_to user_path(current_user)
  end

  private

  def trip_params
    params.require(:trip).permit(:country_name, :comment, :recommend, :year)
  end

  # Filter results based on user action on trips index page

  def class_method_conditional
    if params[:year] == "pre-2000"
      @trips = Trip.twentieth_century
    elsif
      params[:year] == "2000-2009"
      @trips = Trip.aughts
    elsif
      params[:year] == "2010-2015"
      @trips = Trip.first_half_of_teens
    elsif
      params[:year] == "2016-present"
      @trips = Trip.second_half_of_teens
    end
  end

  def saving_trip
    if  @trip.save
      #redirect_to users_path
      render json: @trip, status: 201
    else
      render 'new'
    end
  end

end

app/helpers/trips_helper.rb
module TripsHelper

  def recommended?(trip)
      if trip.recommend?
        "Recommended? Yes"
      else
        "Recommended? No"
      end
  end
end

app/views/trips/_form.html.erb
<h1>Add a new trip:</h1>

<%= form_for @trip, html: {id: "new-trip-form"} do |f| %>

  <%= f.label :country_name %>
  <%= f.collection_select :country, Country.all, :name, :name, :include_blank => true %>

  <h2>Or add a new country:</h2>
  <%= f.label :country %>
  <%= f.text_field :country_name %> <br>

  <h3>Other details:</h3>
  Year Visited:<%= f.text_field :year %><br>
  <%= f.label :recommend? %>
  <%= f.check_box :recommend?, {}, "true", "false"%><br>

  <%= f.label :comment %>
  <%= f.text_area :comment %><br>
  <%= f.submit %>


<% end %>

<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
<script type="text/javascript">
  $(function () {
    $('form').submit(function(event) {
      event.preventDefault();
      let values = $(this).serialize();
      let posting = $.post('/trips', values);
      posting.done(function(data) {
        postTrip(data)
      }).done(document.getElementById("new-trip-form").reset())
    })
  })
</script>

app/views/trips/edit.html.erb
<% if @trip.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@trip.errors.count, "error") %>
      prohibited this account from being saved:
    </h2>

    <ul>
    <% @trip.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<h1>Have your thoughts evolved on this trip? Share them here!</h1>

<%= form_for @trip do |f| %>
  <%= f.label :recommend? %>
  <%= f.check_box :recommend %><br>

  <%= f.label :comment %>
  <%= f.text_area :comment %><br>
  <%= f.submit %>

<% end %>

app/views/trips/index.html.erb
<h1>Filter by year:</h1>

<%= form_tag("/trips", method: "get") do %>
  <%= select_tag "year", options_for_select(["pre-2000", "2000-2009", "2010-2015", "2016-present"]), include_blank: true %><br>
  <%= submit_tag "Filter" %><br>
  <% end %>

<br>


<!-- Will only render trips if a filter has been picked by the user -->
<% if @filter %>
<% @trips.each do |trip| %>
<div class="user">

<%= trip.year %><br>
<%= trip.country.name %><br>
<%= link_to trip.user.name, user_path(trip.user) %><br>
<%= link_to trip.comment, user_trip_path(trip.user, trip) %><br>
<%= recommended? trip%><br>

</div>
  <% end %>
<% end %>

<%= link_to "Back to all trips", users_path %><br>
<%= link_to "Log Out", logout_path %><br>

app/views/trips/new.html.erb
<% if @trip.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@trip.errors.count, "error") %>
      prohibited this account from being saved:
    </h2>

    <ul>
    <% @trip.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<h1>Add a new trip:</h1>

<%= render partial: "form", locals: {trip: @trip} %> 

app/views/trips/show.html.erb
<h1 class="js-next-trip-country" data-country-id="<%=@trip.country.id%>"><%=@trip.country.name%></h1>


<h1><%= link_to @trip.user.name, user_path(@trip.user)%></h1>

<h4 class="next-trip-id">Explorers Unite Trip ID: <%= @trip.id %></h4>
<h3 class="next-trip-comment">Comment: <%= @trip.comment %></h3>
<h4 class="next-trip-year">Year Visited: <%= @trip.year %></h4>
<h4 class="next-trip-recommend"><%= recommended? @trip %></h4>

<!-- Must refactor to allow for ability to edit and delete trip based on trip being currently viewed. Currently it would act on trip originally viewed before 'next trip' was clicked  -->

<!-- <% if @trip.user == current_user %> -->
<%#= link_to "Edit the comment for this trip", edit_user_trip_path(@trip.user, @trip) %><br>
<%#= link_to "Delete this trip", trip_path(@trip), method: :delete, data: {confirm: "Are you sure you want to delete this trip?"} %>
 <!-- <% end %> -->
<br>
<br>


<a class="js-other-users" data-user-id="<%=@trip.user.id%>" data-country-id="<%=@trip.country.id%>" href="#">Click to see other users that have been to this country</a><br>
<div id="other-users">

</div>
<br>
<br>

<%= link_to "Back to all trips", users_path %><br>
<a class="js-next-trip" data-user-id="<%=@trip.user.id%>" data-trip-id="<%=@trip.id%>" href="#">See the next trip by this user</a>

<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
<script type="text/javascript">
  $(function () {
    $(".js-next-trip").on("click", function(e) {
      e.preventDefault()
      fetchNextTrip()
    })
  })

</script>

<script type="text/javascript">
  $(function () {
    $(".js-other-users").on("click", function(e) {
      e.preventDefault();
      getOtherUsers();
    })
  })
</script>