config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static#home'

  resources :users do
    resources :trips, only: [:index, :show, :new, :edit]
  end

  resources :trips

  resources :countries

  get '/users/most_trips_taken' => 'users#most_trips_taken'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#create'

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :trips
  has_many :countries, through: :trips
  validates :name, presence: true
  validates :favorite_country, presence: true, unless: :logged_in_through_facebook
  validates :password, length: {minimum: 6}, unless: :logged_in_through_facebook
  validates :email, uniqueness: true
  scope :most_trips_taken, -> { joins(:trips).group('trips.user_id').order("count(trips.user_id) desc").limit(1)}

  def logged_in_through_facebook
    #uid is an attribute only given if logged on through facebook
    !!self.uid
  end

  def self.find_or_create_by_omniauth(auth_hash)
    oauth_email = auth_hash['info']['email']
    # Either finding a user who has already logged on through Facebook through their email or creating one based on their email and name given by Facebook Oauth. The password is randomly generated and uid is a value that lets the program know the user was created through FB 
      where(:email => oauth_email).first_or_create do |user|
        user.password = SecureRandom.hex
        user.name = auth_hash['info']['name']
        user.uid = auth_hash['uid']
      end
    end





end

app/controllers/users_controller.rb
require 'pry'
class UsersController < ApplicationController
  before_action :require_login
  skip_before_action :require_login, only: [:new, :create]


  def index
    @users = User.all
  end

  def show
    if params[:id] == "most_trips_taken"
      @user = User.most_trips_taken.first
      render 'most_trips_taken'

    else
    @user = User.find_by(id: params[:id])
    #form_for on users/show page can wrap around newly built @trip 
    @trip = @user.trips.build
    respond_to do |format|
      format.html {render :show}
      format.json {render json: @user}
    end
  end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end


private
  def user_params
    params.require(:user).permit(:name, :email, :password, :favorite_country)
  end

end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
Name: <%=f.text_field :name %><br>
E-mail: <%=f.text_field :email %><br>
<%# f.label "Password:" %>
Password: <%= f.password_field :password %><br>
Favorite Country: <%= f.text_field :favorite_country %><br>
<%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@user.errors.count, "error") %>
      prohibited this account from being saved:
    </h2>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<h1>Edit your information!</h1>

<%= render partial: "form", locals: {user: @user} %>

app/views/users/index.html.erb
<h1>Welcome <%= current_user.name%>. Browse users to see their trips:</h1>

<%= link_to "Filter trips by year", trips_path %><br>
<%= link_to "Filter by country", countries_path %><br>
<%= link_to "Your Page", user_path(current_user) %><br>


<div class="user">
<% @users.each do |user| %>
<% if !tripless user %>
  <%= link_to user.name.upcase, user_path(user) %><br>

<% end %>
<% end %>
</div>


<br>
<br>


<%= link_to "Log Out", logout_path %>

app/views/users/most_trips_taken.html.erb
<h1><%= @user.name %> has taken the most trips.</h1>

<h2>They have taken <%= @user.trips.size %> trips.</h2>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@user.errors.count, "error") %>
      prohibited this account from being saved:
    </h2>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<h1>Create an account!</h1>

<%= form_for @user do |f| %>
Name: <%=f.text_field :name %><br>
E-mail: <%=f.text_field :email %><br>
Password: <%= f.text_field :password %><br>
Favorite Country: <%= f.text_field :favorite_country %><br>
<%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>'s Page!</h1><br>

<h2> This user's favorite country is: <%= @user.favorite_country%></h2>
<% if @user.trips.empty? %>
<h2>There are no trips to show yet.</h2>
<% else %>

<a class="js-load-trips" href="#" data-user-id="<%=@user.id%>">See this user's trips:</a>

<div id="trips">
</div>
  <% end %>

<br>
<br>

<% if current_user.id == @user.id %>

<%= render partial: "trips/form", locals: {trip: @trip} %>

<%= link_to "Add a Trip", new_user_trip_path(@user) %><br>
<%= link_to "Edit Info", edit_user_path(@user) %> <br>
<%= link_to "Log Out", logout_path %><br>
<% end %>

<%= link_to "See all users' trips", users_path %> <br>

<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
<script type="text/javascript" charset="utf-8">
$(function () {
  $(".js-load-trips").one('click', function(e) {
    e.preventDefault();
    loadTrips();
})
})
</script>

<script src="//cdnjs.cloudflare.com/ajax/libs/handlebars.js/1.3.0/handlebars.min.js"></script>
<script id="trip-template" type="text/x-handlebars-template">
  {{#each this}}
    <section>
      <h3>Explorers Unite Trip Id: {{this.id}}</h3>
      <h3>{{this.country.name}}</h3>
      <p>Comment:{{this.comment}}</p>
      <a href="/users/{{user.id}}/trips/{{this.id}}">See More Details About This Trip</a>
    </section>
  {{/each}}
</script>