config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static#home'

  resources :users do
    resources :trips, only: [:index, :show, :new, :edit]
  end

  resources :trips

  resources :countries

  get '/users/most_trips_taken' => 'users#most_trips_taken'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#create'

end

app/models/country.rb
class Country < ApplicationRecord
  has_many :trips
  has_many :users, through: :trips
  validates :name, presence: true 
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :require_login

  def index
    @countries = Country.all
  end

  def show
    @country = Country.find_by(id: params[:id])
    respond_to do |format|
      format.html {render :show}
      format.json {render json: @country}
    end
  end

end

app/helpers/countries_helper.rb
module CountriesHelper

  def tripless(country)
      country.trips.empty?
  end
end

app/views/countries/index.html.erb
<h1>All the countries our Explorers have visited!</h1><br>
<h2>Click a country to see the trips that have gone there.</h2><br>



<% @countries.each do |country| %>
<% if !tripless country %>
<%= link_to country.name.upcase, country_path(country) %> <%= pluralize(country.trips.count, "trip") %><br>
<% end %> 
<% end %>

<br>
<br>
<%= link_to "Back to all trips", users_path %><br>
<%= link_to "Log Out", logout_path %><br>

app/views/countries/show.html.erb
<%= @country.name %><br>

<% @country.trips.each do |trip| %>
  <%= link_to trip.user.name, user_path(trip.user) %><br>
  <%= trip.comment %>  <br>
  <%= recommended? trip %> <br>
  <% end %>

  <br>
  <br>

  <%= link_to "Back to all countries", countries_path %><br>
  <%= link_to "Back to all trips", users_path %><br>